basePath: /api/v1
definitions:
  dto.AddModuleConfigReq:
    properties:
      key:
        type: string
      module_id:
        type: integer
      value:
        type: string
    type: object
  dto.AddSiteReq:
    properties:
      name:
        type: string
      profile:
        type: string
      url:
        type: string
    type: object
  dto.AddSiteResp:
    properties:
      code:
        type: integer
      id:
        type: integer
      msg:
        type: string
      opt:
        type: string
    type: object
  dto.ApplicationSaveReq:
    properties:
      cleword_schema_version:
        type: string
      code:
        description: applicationCode
        type: string
      name:
        description: Namespace            string `json:"namespace"`
        type: string
      namespace:
        type: string
      publication:
        description: Resolved             string `json:"resolved"`    // zip 课程包地址
          URL
        type: integer
      resolved:
        description: zip 课程包地址 URL
        type: string
      site_id:
        description: site 点 id
        type: integer
      version:
        type: string
    type: object
  dto.BookContent:
    properties:
      about_author:
        description: 关于作者
        type: string
      author:
        description: 书籍的作者
        type: string
      book_isbn:
        description: 书籍的 isbn 号
        type: string
      content_text_url:
        description: 文本地址
        type: string
      cover_url:
        description: 封面url
        type: string
      essential:
        description: 一句话概要
        type: string
      framework:
        description: 书籍的思维导图
        type: string
      free:
        description: 书籍是否免费
        type: boolean
      gain:
        description: 读完本书你将获得
        type: string
      introduction:
        description: 本书简介
        type: string
      name:
        description: 书籍名称
        type: string
      recommendation_ranking:
        description: 推荐等级
        type: integer
      tag:
        description: 标签
        type: string
      version:
        description: 书籍版本
        type: string
    type: object
  dto.BookTTLRes:
    properties:
      code:
        type: integer
      data:
        properties:
          url:
            description: 生成的文稿 url
            type: string
        type: object
      msg:
        type: string
      opt:
        type: string
    type: object
  dto.FinanceApplicationSaveReq:
    properties:
      cleword_schema_version:
        type: string
      code:
        description: applicationCode
        type: string
      name:
        description: Namespace            string `json:"namespace"`
        type: string
      publication:
        description: Resolved             string `json:"resolved"`    // zip 课程包地址
          URL
        type: integer
      resolved_by_direct:
        description: 财商不再需要财商Namespace
        type: string
      site_id:
        description: site 点 id
        type: integer
      version:
        type: string
    type: object
  dto.GetSiteDetailResp:
    properties:
      site:
        $ref: '#/definitions/dto.Site'
    type: object
  dto.Result:
    properties:
      code:
        type: integer
      msg:
        type: string
      opt:
        type: string
    type: object
  dto.ResultWithData:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
      opt:
        type: string
    type: object
  dto.ResultWithFid:
    properties:
      code:
        type: integer
      data:
        properties:
          fid:
            type: string
        type: object
      msg:
        type: string
      opt:
        type: string
    type: object
  dto.ResultWithQiniuToken:
    properties:
      code:
        type: integer
      data:
        properties:
          domain:
            type: string
          uploadToken:
            type: string
        type: object
      msg:
        type: string
      opt:
        type: string
    type: object
  dto.Site:
    properties:
      blockedReason:
        type: string
      blockedTime:
        type: integer
      id:
        type: integer
      name:
        type: string
      profile:
        type: string
      status:
        type: integer
      url:
        type: string
    type: object
  dto.UpdateSiteReq:
    properties:
      id:
        type: integer
      profile:
        type: string
    type: object
info:
  contact:
    email: zhoujin@forchange.tech
    name: 周进、谢东阳
    url: https://git.forchange.cn/zhoujin
  description: 产品管理系统
  termsOfService: https://git.forchange.cn/manage/product
  title: 产品管理系统
  version: "1.0"
paths:
  /applications:
    delete:
      consumes:
      - application/json
      description: 通过 application_id 删除 application
      parameters:
      - description: application id
        in: query
        name: application_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Result'
      summary: 通过 application_id 删除 application
      tags:
      - manager
    get:
      consumes:
      - application/json
      description: 通过 Site_id 查询applications
      parameters:
      - description: 每一个页application数量, 默认20
        in: query
        name: page_count
        type: integer
      - description: 默认第一页；从1开始
        in: query
        name: page_num
        type: integer
      - description: site 的 id
        in: query
        name: site_id
        required: true
        type: integer
      - description: application的namespace
        in: query
        name: namespace
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Result'
      summary: 通过 Site_id 查询applications
      tags:
      - manager
    post:
      consumes:
      - application/json
      description: 获取当前场景文件获取功能：
      parameters:
      - description: application 信息
        in: body
        name: app
        required: true
        schema:
          $ref: '#/definitions/dto.ApplicationSaveReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Result'
        "400":
          description: 参数格式有误
          schema:
            $ref: '#/definitions/dto.Result'
        "422":
          description: 参数值有误
          schema:
            $ref: '#/definitions/dto.Result'
      summary: Cleword 课程包应用上传
      tags:
      - manager
  /applications/brief:
    get:
      consumes:
      - application/json
      description: 通过 Site_id 查询applications 名称 版本
      parameters:
      - description: site 的 id
        in: query
        name: site_id
        type: integer
      - description: application code
        in: query
        name: application_code
        type: integer
      - description: application的namespace
        in: query
        name: namespace
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Result'
      summary: 通过 Site_id 查询applications 名称 版本
      tags:
      - manager
  /applications/details:
    get:
      consumes:
      - application/json
      description: 通过 application_code 查询applications的详情
      parameters:
      - description: application code
        in: query
        name: application_code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Result'
      summary: 通过 application_code 查询applications的详情
      tags:
      - manager
  /book:
    post:
      consumes:
      - application/json
      description: 上传书籍详情：
      parameters:
      - description: 书籍内容文稿信息
        in: body
        name: app
        required: true
        schema:
          $ref: '#/definitions/dto.BookContent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BookTTLRes'
        "400":
          description: 参数格式有误
          schema:
            $ref: '#/definitions/dto.Result'
        "422":
          description: 参数值有误
          schema:
            $ref: '#/definitions/dto.Result'
      summary: Book 上传书籍详情页面信息
      tags:
      - book
  /bool/ttl:
    post:
      consumes:
      - application/json
      description: 生成对应的文稿音频：
      parameters:
      - description: 书籍内容文稿信息
        in: body
        name: app
        required: true
        schema:
          $ref: '#/definitions/dto.BookContent'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BookTTLRes'
        "400":
          description: 参数格式有误
          schema:
            $ref: '#/definitions/dto.Result'
        "422":
          description: 参数值有误
          schema:
            $ref: '#/definitions/dto.Result'
      summary: Book 生成对应的文稿音频
      tags:
      - book
  /fid:
    get:
      consumes:
      - application/json
      description: 获取fid
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResultWithFid'
      summary: 获取fid
      tags:
      - manager
  /finance/applications:
    delete:
      consumes:
      - application/json
      description: 通过 application_code 删除 application
      parameters:
      - description: application code
        in: query
        name: application_code
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Result'
      summary: 通过 application_code 删除 application
      tags:
      - manager
    post:
      consumes:
      - application/json
      description: 获取当前场景文件获取功能：
      parameters:
      - description: 课程信息
        in: body
        name: app
        required: true
        schema:
          $ref: '#/definitions/dto.FinanceApplicationSaveReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Result'
        "400":
          description: 参数格式有误
          schema:
            $ref: '#/definitions/dto.Result'
        "422":
          description: 参数值有误
          schema:
            $ref: '#/definitions/dto.Result'
      summary: 财商课程包应用上传
      tags:
      - manager
  /finance/applications/all_detail:
    get:
      consumes:
      - application/json
      parameters:
      - description: application code
        in: query
        name: application_code
        required: true
        type: string
      - description: application版本号
        in: query
        name: version
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResultWithData'
      summary: 根据 application_code和version获取application-module-moduleConfig信息
      tags:
      - manager
  /finance/module-config:
    post:
      consumes:
      - application/json
      description: 保存 moduleConfig 信息
      parameters:
      - description: config信息
        in: body
        name: app
        required: true
        schema:
          $ref: '#/definitions/dto.AddModuleConfigReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResultWithData'
      summary: 保存 moduleConfig 信息
      tags:
      - manager
  /qiniu/token:
    get:
      consumes:
      - application/json
      description: 获取七牛云 token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResultWithQiniuToken'
      summary: 获取七牛云 token
      tags:
      - manager
  /site/:id:
    put:
      consumes:
      - application/json
      description: 更新 site
      parameters:
      - description: site_id
        in: path
        name: id
        required: true
        type: integer
      - description: site 更新内容
        in: body
        name: app
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateSiteReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Result'
      summary: 更新 site
      tags:
      - manager
  /site/add:
    post:
      consumes:
      - application/json
      description: 保存 site 信息
      parameters:
      - description: site 信息
        in: body
        name: app
        required: true
        schema:
          $ref: '#/definitions/dto.AddSiteReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AddSiteResp'
      summary: 保存 site 信息
      tags:
      - manager
  /site/detail:
    get:
      consumes:
      - application/json
      description: 获取 site 详情
      parameters:
      - description: site 的 id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.GetSiteDetailResp'
      summary: 获取 site 详情
      tags:
      - manager
  /site/list:
    get:
      consumes:
      - application/json
      description: 获取 Site 列表
      parameters:
      - description: 每一个页 site 数量, 默认20
        in: query
        name: limit
        type: integer
      - description: 当前页数量
        in: query
        name: pageNum
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ResultWithData'
      summary: 获取 Site 列表
      tags:
      - manager
schemes:
- http
swagger: "2.0"
